/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CreativesRouteImport } from './routes/creatives'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LabsProductDataRouteImport } from './routes/labs.product-data'
import { Route as LabsProductHistoryRouteImport } from './routes/labs.product-history'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ApiProductsSearchRouteImport } from './routes/api/products/search'
import { Route as ApiLabsProductsIndexRouteImport } from './routes/api/labs/products/index'
import { Route as ApiLabsProductsIngestRouteImport } from './routes/api/labs/products/ingest'
import { Route as ApiLabsProductsProductIdHistoryRouteImport } from './routes/api/labs/products/$productId.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativesRoute = CreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsProductDataRoute = LabsProductDataRouteImport.update({
  id: '/labs/product-data',
  path: '/labs/product-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsProductHistoryRoute = LabsProductHistoryRouteImport.update({
  id: '/labs/product-history',
  path: '/labs/product-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsSearchRoute = ApiProductsSearchRouteImport.update({
  id: '/api/products/search',
  path: '/api/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsProductsIndexRoute = ApiLabsProductsIndexRouteImport.update({
  id: '/api/labs/products/',
  path: '/api/labs/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsProductsIngestRoute = ApiLabsProductsIngestRouteImport.update({
  id: '/api/labs/products/ingest',
  path: '/api/labs/products/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsProductsProductIdHistoryRoute =
  ApiLabsProductsProductIdHistoryRouteImport.update({
    id: '/api/labs/products/$productId/history',
    path: '/api/labs/products/$productId/history',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/creatives': typeof CreativesRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/labs/product-data': typeof LabsProductDataRoute
  '/labs/product-history': typeof LabsProductHistoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/labs/products/ingest': typeof ApiLabsProductsIngestRoute
  '/api/labs/products/': typeof ApiLabsProductsIndexRoute
  '/api/labs/products/$productId/history': typeof ApiLabsProductsProductIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/creatives': typeof CreativesRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/labs/product-data': typeof LabsProductDataRoute
  '/labs/product-history': typeof LabsProductHistoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/labs/products/ingest': typeof ApiLabsProductsIngestRoute
  '/api/labs/products': typeof ApiLabsProductsIndexRoute
  '/api/labs/products/$productId/history': typeof ApiLabsProductsProductIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/creatives': typeof CreativesRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/labs/product-data': typeof LabsProductDataRoute
  '/labs/product-history': typeof LabsProductHistoryRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/labs/products/ingest': typeof ApiLabsProductsIngestRoute
  '/api/labs/products/': typeof ApiLabsProductsIndexRoute
  '/api/labs/products/$productId/history': typeof ApiLabsProductsProductIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/creatives'
    | '/library'
    | '/settings'
    | '/labs/product-data'
    | '/labs/product-history'
    | '/products/$productId'
    | '/products/'
    | '/api/products/search'
    | '/api/labs/products/ingest'
    | '/api/labs/products/'
    | '/api/labs/products/$productId/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/creatives'
    | '/library'
    | '/settings'
    | '/labs/product-data'
    | '/labs/product-history'
    | '/products/$productId'
    | '/products'
    | '/api/products/search'
    | '/api/labs/products/ingest'
    | '/api/labs/products'
    | '/api/labs/products/$productId/history'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/creatives'
    | '/library'
    | '/settings'
    | '/labs/product-data'
    | '/labs/product-history'
    | '/products/$productId'
    | '/products/'
    | '/api/products/search'
    | '/api/labs/products/ingest'
    | '/api/labs/products/'
    | '/api/labs/products/$productId/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CreativesRoute: typeof CreativesRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  LabsProductDataRoute: typeof LabsProductDataRoute
  LabsProductHistoryRoute: typeof LabsProductHistoryRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiProductsSearchRoute: typeof ApiProductsSearchRoute
  ApiLabsProductsIngestRoute: typeof ApiLabsProductsIngestRoute
  ApiLabsProductsIndexRoute: typeof ApiLabsProductsIndexRoute
  ApiLabsProductsProductIdHistoryRoute: typeof ApiLabsProductsProductIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatives': {
      id: '/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof CreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/product-data': {
      id: '/labs/product-data'
      path: '/labs/product-data'
      fullPath: '/labs/product-data'
      preLoaderRoute: typeof LabsProductDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/product-history': {
      id: '/labs/product-history'
      path: '/labs/product-history'
      fullPath: '/labs/product-history'
      preLoaderRoute: typeof LabsProductHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/search': {
      id: '/api/products/search'
      path: '/api/products/search'
      fullPath: '/api/products/search'
      preLoaderRoute: typeof ApiProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/products/': {
      id: '/api/labs/products/'
      path: '/api/labs/products'
      fullPath: '/api/labs/products/'
      preLoaderRoute: typeof ApiLabsProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/products/ingest': {
      id: '/api/labs/products/ingest'
      path: '/api/labs/products/ingest'
      fullPath: '/api/labs/products/ingest'
      preLoaderRoute: typeof ApiLabsProductsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/products/$productId/history': {
      id: '/api/labs/products/$productId/history'
      path: '/api/labs/products/$productId/history'
      fullPath: '/api/labs/products/$productId/history'
      preLoaderRoute: typeof ApiLabsProductsProductIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CreativesRoute: CreativesRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  LabsProductDataRoute: LabsProductDataRoute,
  LabsProductHistoryRoute: LabsProductHistoryRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiProductsSearchRoute: ApiProductsSearchRoute,
  ApiLabsProductsIngestRoute: ApiLabsProductsIngestRoute,
  ApiLabsProductsIndexRoute: ApiLabsProductsIndexRoute,
  ApiLabsProductsProductIdHistoryRoute: ApiLabsProductsProductIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
