/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CreativesRouteImport } from './routes/creatives'
import { Route as DiscoveryRouteImport } from './routes/discovery'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as LabsProductDataRouteImport } from './routes/labs.product-data'
import { Route as LabsProductHistoryRouteImport } from './routes/labs.product-history'
import { Route as LabsProductMetricsRouteImport } from './routes/labs.product-metrics'
import { Route as LabsProductTrendsRouteImport } from './routes/labs.product-trends'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as ApiDiscoveryNichesRouteImport } from './routes/api/discovery/niches'
import { Route as ApiDiscoveryQuickSearchRouteImport } from './routes/api/discovery/quick-search'
import { Route as ApiProductsIndexRouteImport } from './routes/api/products/index'
import { Route as ApiProductsProductIdRouteImport } from './routes/api/products/$productId'
import { Route as ApiProductsSearchRouteImport } from './routes/api/products/search'
import { Route as ApiAuthTiktokCallbackRouteImport } from './routes/api/auth/tiktok/callback'
import { Route as ApiDiscoveryProductsProductIdRouteImport } from './routes/api/discovery/products/$productId'
import { Route as ApiDiscoverySearchesIndexRouteImport } from './routes/api/discovery/searches/index'
import { Route as ApiDiscoverySearchesSearchIdRouteImport } from './routes/api/discovery/searches/$searchId'
import { Route as ApiLabsProductsIndexRouteImport } from './routes/api/labs/products/index'
import { Route as ApiLabsProductsIngestRouteImport } from './routes/api/labs/products/ingest'
import { Route as ApiLabsProductsMetricsRouteImport } from './routes/api/labs/products/metrics'
import { Route as ApiLabsProductsTrendsRouteImport } from './routes/api/labs/products/trends'
import { Route as ApiLabsTiktokOfficialProductSearchRouteImport } from './routes/api/labs/tiktok-official/product-search'
import { Route as ApiDiscoverySearchesSearchIdRunRouteImport } from './routes/api/discovery/searches/$searchId.run'
import { Route as ApiLabsProductsProductIdHistoryRouteImport } from './routes/api/labs/products/$productId.history'
import { Route as ApiLabsProductsProductIdTrendRouteImport } from './routes/api/labs/products/$productId.trend'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativesRoute = CreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveryRoute = DiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsProductDataRoute = LabsProductDataRouteImport.update({
  id: '/labs/product-data',
  path: '/labs/product-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsProductHistoryRoute = LabsProductHistoryRouteImport.update({
  id: '/labs/product-history',
  path: '/labs/product-history',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsProductMetricsRoute = LabsProductMetricsRouteImport.update({
  id: '/labs/product-metrics',
  path: '/labs/product-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsProductTrendsRoute = LabsProductTrendsRouteImport.update({
  id: '/labs/product-trends',
  path: '/labs/product-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryNichesRoute = ApiDiscoveryNichesRouteImport.update({
  id: '/api/discovery/niches',
  path: '/api/discovery/niches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryQuickSearchRoute = ApiDiscoveryQuickSearchRouteImport.update({
  id: '/api/discovery/quick-search',
  path: '/api/discovery/quick-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIndexRoute = ApiProductsIndexRouteImport.update({
  id: '/api/products/',
  path: '/api/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsProductIdRoute = ApiProductsProductIdRouteImport.update({
  id: '/api/products/$productId',
  path: '/api/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsSearchRoute = ApiProductsSearchRouteImport.update({
  id: '/api/products/search',
  path: '/api/products/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTiktokCallbackRoute = ApiAuthTiktokCallbackRouteImport.update({
  id: '/api/auth/tiktok/callback',
  path: '/api/auth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoveryProductsProductIdRoute =
  ApiDiscoveryProductsProductIdRouteImport.update({
    id: '/api/discovery/products/$productId',
    path: '/api/discovery/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiscoverySearchesIndexRoute =
  ApiDiscoverySearchesIndexRouteImport.update({
    id: '/api/discovery/searches/',
    path: '/api/discovery/searches/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiscoverySearchesSearchIdRoute =
  ApiDiscoverySearchesSearchIdRouteImport.update({
    id: '/api/discovery/searches/$searchId',
    path: '/api/discovery/searches/$searchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLabsProductsIndexRoute = ApiLabsProductsIndexRouteImport.update({
  id: '/api/labs/products/',
  path: '/api/labs/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsProductsIngestRoute = ApiLabsProductsIngestRouteImport.update({
  id: '/api/labs/products/ingest',
  path: '/api/labs/products/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsProductsMetricsRoute = ApiLabsProductsMetricsRouteImport.update({
  id: '/api/labs/products/metrics',
  path: '/api/labs/products/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsProductsTrendsRoute = ApiLabsProductsTrendsRouteImport.update({
  id: '/api/labs/products/trends',
  path: '/api/labs/products/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabsTiktokOfficialProductSearchRoute =
  ApiLabsTiktokOfficialProductSearchRouteImport.update({
    id: '/api/labs/tiktok-official/product-search',
    path: '/api/labs/tiktok-official/product-search',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDiscoverySearchesSearchIdRunRoute =
  ApiDiscoverySearchesSearchIdRunRouteImport.update({
    id: '/run',
    path: '/run',
    getParentRoute: () => ApiDiscoverySearchesSearchIdRoute,
  } as any)
const ApiLabsProductsProductIdHistoryRoute =
  ApiLabsProductsProductIdHistoryRouteImport.update({
    id: '/api/labs/products/$productId/history',
    path: '/api/labs/products/$productId/history',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLabsProductsProductIdTrendRoute =
  ApiLabsProductsProductIdTrendRouteImport.update({
    id: '/api/labs/products/$productId/trend',
    path: '/api/labs/products/$productId/trend',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/creatives': typeof CreativesRoute
  '/discovery': typeof DiscoveryRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/labs/product-data': typeof LabsProductDataRoute
  '/labs/product-history': typeof LabsProductHistoryRoute
  '/labs/product-metrics': typeof LabsProductMetricsRoute
  '/labs/product-trends': typeof LabsProductTrendsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/api/discovery/niches': typeof ApiDiscoveryNichesRoute
  '/api/discovery/quick-search': typeof ApiDiscoveryQuickSearchRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/auth/tiktok/callback': typeof ApiAuthTiktokCallbackRoute
  '/api/discovery/products/$productId': typeof ApiDiscoveryProductsProductIdRoute
  '/api/discovery/searches/$searchId': typeof ApiDiscoverySearchesSearchIdRouteWithChildren
  '/api/labs/products/ingest': typeof ApiLabsProductsIngestRoute
  '/api/labs/products/metrics': typeof ApiLabsProductsMetricsRoute
  '/api/labs/products/trends': typeof ApiLabsProductsTrendsRoute
  '/api/labs/tiktok-official/product-search': typeof ApiLabsTiktokOfficialProductSearchRoute
  '/api/discovery/searches/': typeof ApiDiscoverySearchesIndexRoute
  '/api/labs/products/': typeof ApiLabsProductsIndexRoute
  '/api/discovery/searches/$searchId/run': typeof ApiDiscoverySearchesSearchIdRunRoute
  '/api/labs/products/$productId/history': typeof ApiLabsProductsProductIdHistoryRoute
  '/api/labs/products/$productId/trend': typeof ApiLabsProductsProductIdTrendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/creatives': typeof CreativesRoute
  '/discovery': typeof DiscoveryRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/labs/product-data': typeof LabsProductDataRoute
  '/labs/product-history': typeof LabsProductHistoryRoute
  '/labs/product-metrics': typeof LabsProductMetricsRoute
  '/labs/product-trends': typeof LabsProductTrendsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products': typeof ProductsIndexRoute
  '/api/discovery/niches': typeof ApiDiscoveryNichesRoute
  '/api/discovery/quick-search': typeof ApiDiscoveryQuickSearchRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/products': typeof ApiProductsIndexRoute
  '/api/auth/tiktok/callback': typeof ApiAuthTiktokCallbackRoute
  '/api/discovery/products/$productId': typeof ApiDiscoveryProductsProductIdRoute
  '/api/discovery/searches/$searchId': typeof ApiDiscoverySearchesSearchIdRouteWithChildren
  '/api/labs/products/ingest': typeof ApiLabsProductsIngestRoute
  '/api/labs/products/metrics': typeof ApiLabsProductsMetricsRoute
  '/api/labs/products/trends': typeof ApiLabsProductsTrendsRoute
  '/api/labs/tiktok-official/product-search': typeof ApiLabsTiktokOfficialProductSearchRoute
  '/api/discovery/searches': typeof ApiDiscoverySearchesIndexRoute
  '/api/labs/products': typeof ApiLabsProductsIndexRoute
  '/api/discovery/searches/$searchId/run': typeof ApiDiscoverySearchesSearchIdRunRoute
  '/api/labs/products/$productId/history': typeof ApiLabsProductsProductIdHistoryRoute
  '/api/labs/products/$productId/trend': typeof ApiLabsProductsProductIdTrendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/creatives': typeof CreativesRoute
  '/discovery': typeof DiscoveryRoute
  '/library': typeof LibraryRoute
  '/settings': typeof SettingsRoute
  '/api/dashboard': typeof ApiDashboardRoute
  '/labs/product-data': typeof LabsProductDataRoute
  '/labs/product-history': typeof LabsProductHistoryRoute
  '/labs/product-metrics': typeof LabsProductMetricsRoute
  '/labs/product-trends': typeof LabsProductTrendsRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/': typeof ProductsIndexRoute
  '/api/discovery/niches': typeof ApiDiscoveryNichesRoute
  '/api/discovery/quick-search': typeof ApiDiscoveryQuickSearchRoute
  '/api/products/$productId': typeof ApiProductsProductIdRoute
  '/api/products/search': typeof ApiProductsSearchRoute
  '/api/products/': typeof ApiProductsIndexRoute
  '/api/auth/tiktok/callback': typeof ApiAuthTiktokCallbackRoute
  '/api/discovery/products/$productId': typeof ApiDiscoveryProductsProductIdRoute
  '/api/discovery/searches/$searchId': typeof ApiDiscoverySearchesSearchIdRouteWithChildren
  '/api/labs/products/ingest': typeof ApiLabsProductsIngestRoute
  '/api/labs/products/metrics': typeof ApiLabsProductsMetricsRoute
  '/api/labs/products/trends': typeof ApiLabsProductsTrendsRoute
  '/api/labs/tiktok-official/product-search': typeof ApiLabsTiktokOfficialProductSearchRoute
  '/api/discovery/searches/': typeof ApiDiscoverySearchesIndexRoute
  '/api/labs/products/': typeof ApiLabsProductsIndexRoute
  '/api/discovery/searches/$searchId/run': typeof ApiDiscoverySearchesSearchIdRunRoute
  '/api/labs/products/$productId/history': typeof ApiLabsProductsProductIdHistoryRoute
  '/api/labs/products/$productId/trend': typeof ApiLabsProductsProductIdTrendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/creatives'
    | '/discovery'
    | '/library'
    | '/settings'
    | '/api/dashboard'
    | '/labs/product-data'
    | '/labs/product-history'
    | '/labs/product-metrics'
    | '/labs/product-trends'
    | '/products/$productId'
    | '/products/'
    | '/api/discovery/niches'
    | '/api/discovery/quick-search'
    | '/api/products/$productId'
    | '/api/products/search'
    | '/api/products/'
    | '/api/auth/tiktok/callback'
    | '/api/discovery/products/$productId'
    | '/api/discovery/searches/$searchId'
    | '/api/labs/products/ingest'
    | '/api/labs/products/metrics'
    | '/api/labs/products/trends'
    | '/api/labs/tiktok-official/product-search'
    | '/api/discovery/searches/'
    | '/api/labs/products/'
    | '/api/discovery/searches/$searchId/run'
    | '/api/labs/products/$productId/history'
    | '/api/labs/products/$productId/trend'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/creatives'
    | '/discovery'
    | '/library'
    | '/settings'
    | '/api/dashboard'
    | '/labs/product-data'
    | '/labs/product-history'
    | '/labs/product-metrics'
    | '/labs/product-trends'
    | '/products/$productId'
    | '/products'
    | '/api/discovery/niches'
    | '/api/discovery/quick-search'
    | '/api/products/$productId'
    | '/api/products/search'
    | '/api/products'
    | '/api/auth/tiktok/callback'
    | '/api/discovery/products/$productId'
    | '/api/discovery/searches/$searchId'
    | '/api/labs/products/ingest'
    | '/api/labs/products/metrics'
    | '/api/labs/products/trends'
    | '/api/labs/tiktok-official/product-search'
    | '/api/discovery/searches'
    | '/api/labs/products'
    | '/api/discovery/searches/$searchId/run'
    | '/api/labs/products/$productId/history'
    | '/api/labs/products/$productId/trend'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/creatives'
    | '/discovery'
    | '/library'
    | '/settings'
    | '/api/dashboard'
    | '/labs/product-data'
    | '/labs/product-history'
    | '/labs/product-metrics'
    | '/labs/product-trends'
    | '/products/$productId'
    | '/products/'
    | '/api/discovery/niches'
    | '/api/discovery/quick-search'
    | '/api/products/$productId'
    | '/api/products/search'
    | '/api/products/'
    | '/api/auth/tiktok/callback'
    | '/api/discovery/products/$productId'
    | '/api/discovery/searches/$searchId'
    | '/api/labs/products/ingest'
    | '/api/labs/products/metrics'
    | '/api/labs/products/trends'
    | '/api/labs/tiktok-official/product-search'
    | '/api/discovery/searches/'
    | '/api/labs/products/'
    | '/api/discovery/searches/$searchId/run'
    | '/api/labs/products/$productId/history'
    | '/api/labs/products/$productId/trend'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CreativesRoute: typeof CreativesRoute
  DiscoveryRoute: typeof DiscoveryRoute
  LibraryRoute: typeof LibraryRoute
  SettingsRoute: typeof SettingsRoute
  ApiDashboardRoute: typeof ApiDashboardRoute
  LabsProductDataRoute: typeof LabsProductDataRoute
  LabsProductHistoryRoute: typeof LabsProductHistoryRoute
  LabsProductMetricsRoute: typeof LabsProductMetricsRoute
  LabsProductTrendsRoute: typeof LabsProductTrendsRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ApiDiscoveryNichesRoute: typeof ApiDiscoveryNichesRoute
  ApiDiscoveryQuickSearchRoute: typeof ApiDiscoveryQuickSearchRoute
  ApiProductsProductIdRoute: typeof ApiProductsProductIdRoute
  ApiProductsSearchRoute: typeof ApiProductsSearchRoute
  ApiProductsIndexRoute: typeof ApiProductsIndexRoute
  ApiAuthTiktokCallbackRoute: typeof ApiAuthTiktokCallbackRoute
  ApiDiscoveryProductsProductIdRoute: typeof ApiDiscoveryProductsProductIdRoute
  ApiDiscoverySearchesSearchIdRoute: typeof ApiDiscoverySearchesSearchIdRouteWithChildren
  ApiLabsProductsIngestRoute: typeof ApiLabsProductsIngestRoute
  ApiLabsProductsMetricsRoute: typeof ApiLabsProductsMetricsRoute
  ApiLabsProductsTrendsRoute: typeof ApiLabsProductsTrendsRoute
  ApiLabsTiktokOfficialProductSearchRoute: typeof ApiLabsTiktokOfficialProductSearchRoute
  ApiDiscoverySearchesIndexRoute: typeof ApiDiscoverySearchesIndexRoute
  ApiLabsProductsIndexRoute: typeof ApiLabsProductsIndexRoute
  ApiLabsProductsProductIdHistoryRoute: typeof ApiLabsProductsProductIdHistoryRoute
  ApiLabsProductsProductIdTrendRoute: typeof ApiLabsProductsProductIdTrendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatives': {
      id: '/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof CreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery': {
      id: '/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof DiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/product-data': {
      id: '/labs/product-data'
      path: '/labs/product-data'
      fullPath: '/labs/product-data'
      preLoaderRoute: typeof LabsProductDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/product-history': {
      id: '/labs/product-history'
      path: '/labs/product-history'
      fullPath: '/labs/product-history'
      preLoaderRoute: typeof LabsProductHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/product-metrics': {
      id: '/labs/product-metrics'
      path: '/labs/product-metrics'
      fullPath: '/labs/product-metrics'
      preLoaderRoute: typeof LabsProductMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/product-trends': {
      id: '/labs/product-trends'
      path: '/labs/product-trends'
      fullPath: '/labs/product-trends'
      preLoaderRoute: typeof LabsProductTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/niches': {
      id: '/api/discovery/niches'
      path: '/api/discovery/niches'
      fullPath: '/api/discovery/niches'
      preLoaderRoute: typeof ApiDiscoveryNichesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/quick-search': {
      id: '/api/discovery/quick-search'
      path: '/api/discovery/quick-search'
      fullPath: '/api/discovery/quick-search'
      preLoaderRoute: typeof ApiDiscoveryQuickSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/': {
      id: '/api/products/'
      path: '/api/products'
      fullPath: '/api/products/'
      preLoaderRoute: typeof ApiProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$productId': {
      id: '/api/products/$productId'
      path: '/api/products/$productId'
      fullPath: '/api/products/$productId'
      preLoaderRoute: typeof ApiProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/search': {
      id: '/api/products/search'
      path: '/api/products/search'
      fullPath: '/api/products/search'
      preLoaderRoute: typeof ApiProductsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/tiktok/callback': {
      id: '/api/auth/tiktok/callback'
      path: '/api/auth/tiktok/callback'
      fullPath: '/api/auth/tiktok/callback'
      preLoaderRoute: typeof ApiAuthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/products/$productId': {
      id: '/api/discovery/products/$productId'
      path: '/api/discovery/products/$productId'
      fullPath: '/api/discovery/products/$productId'
      preLoaderRoute: typeof ApiDiscoveryProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/searches/': {
      id: '/api/discovery/searches/'
      path: '/api/discovery/searches'
      fullPath: '/api/discovery/searches/'
      preLoaderRoute: typeof ApiDiscoverySearchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/searches/$searchId': {
      id: '/api/discovery/searches/$searchId'
      path: '/api/discovery/searches/$searchId'
      fullPath: '/api/discovery/searches/$searchId'
      preLoaderRoute: typeof ApiDiscoverySearchesSearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/products/': {
      id: '/api/labs/products/'
      path: '/api/labs/products'
      fullPath: '/api/labs/products/'
      preLoaderRoute: typeof ApiLabsProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/products/ingest': {
      id: '/api/labs/products/ingest'
      path: '/api/labs/products/ingest'
      fullPath: '/api/labs/products/ingest'
      preLoaderRoute: typeof ApiLabsProductsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/products/metrics': {
      id: '/api/labs/products/metrics'
      path: '/api/labs/products/metrics'
      fullPath: '/api/labs/products/metrics'
      preLoaderRoute: typeof ApiLabsProductsMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/products/trends': {
      id: '/api/labs/products/trends'
      path: '/api/labs/products/trends'
      fullPath: '/api/labs/products/trends'
      preLoaderRoute: typeof ApiLabsProductsTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/tiktok-official/product-search': {
      id: '/api/labs/tiktok-official/product-search'
      path: '/api/labs/tiktok-official/product-search'
      fullPath: '/api/labs/tiktok-official/product-search'
      preLoaderRoute: typeof ApiLabsTiktokOfficialProductSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discovery/searches/$searchId/run': {
      id: '/api/discovery/searches/$searchId/run'
      path: '/run'
      fullPath: '/api/discovery/searches/$searchId/run'
      preLoaderRoute: typeof ApiDiscoverySearchesSearchIdRunRouteImport
      parentRoute: typeof ApiDiscoverySearchesSearchIdRoute
    }
    '/api/labs/products/$productId/history': {
      id: '/api/labs/products/$productId/history'
      path: '/api/labs/products/$productId/history'
      fullPath: '/api/labs/products/$productId/history'
      preLoaderRoute: typeof ApiLabsProductsProductIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/labs/products/$productId/trend': {
      id: '/api/labs/products/$productId/trend'
      path: '/api/labs/products/$productId/trend'
      fullPath: '/api/labs/products/$productId/trend'
      preLoaderRoute: typeof ApiLabsProductsProductIdTrendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiDiscoverySearchesSearchIdRouteChildren {
  ApiDiscoverySearchesSearchIdRunRoute: typeof ApiDiscoverySearchesSearchIdRunRoute
}

const ApiDiscoverySearchesSearchIdRouteChildren: ApiDiscoverySearchesSearchIdRouteChildren =
  {
    ApiDiscoverySearchesSearchIdRunRoute: ApiDiscoverySearchesSearchIdRunRoute,
  }

const ApiDiscoverySearchesSearchIdRouteWithChildren =
  ApiDiscoverySearchesSearchIdRoute._addFileChildren(
    ApiDiscoverySearchesSearchIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CreativesRoute: CreativesRoute,
  DiscoveryRoute: DiscoveryRoute,
  LibraryRoute: LibraryRoute,
  SettingsRoute: SettingsRoute,
  ApiDashboardRoute: ApiDashboardRoute,
  LabsProductDataRoute: LabsProductDataRoute,
  LabsProductHistoryRoute: LabsProductHistoryRoute,
  LabsProductMetricsRoute: LabsProductMetricsRoute,
  LabsProductTrendsRoute: LabsProductTrendsRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ApiDiscoveryNichesRoute: ApiDiscoveryNichesRoute,
  ApiDiscoveryQuickSearchRoute: ApiDiscoveryQuickSearchRoute,
  ApiProductsProductIdRoute: ApiProductsProductIdRoute,
  ApiProductsSearchRoute: ApiProductsSearchRoute,
  ApiProductsIndexRoute: ApiProductsIndexRoute,
  ApiAuthTiktokCallbackRoute: ApiAuthTiktokCallbackRoute,
  ApiDiscoveryProductsProductIdRoute: ApiDiscoveryProductsProductIdRoute,
  ApiDiscoverySearchesSearchIdRoute:
    ApiDiscoverySearchesSearchIdRouteWithChildren,
  ApiLabsProductsIngestRoute: ApiLabsProductsIngestRoute,
  ApiLabsProductsMetricsRoute: ApiLabsProductsMetricsRoute,
  ApiLabsProductsTrendsRoute: ApiLabsProductsTrendsRoute,
  ApiLabsTiktokOfficialProductSearchRoute:
    ApiLabsTiktokOfficialProductSearchRoute,
  ApiDiscoverySearchesIndexRoute: ApiDiscoverySearchesIndexRoute,
  ApiLabsProductsIndexRoute: ApiLabsProductsIndexRoute,
  ApiLabsProductsProductIdHistoryRoute: ApiLabsProductsProductIdHistoryRoute,
  ApiLabsProductsProductIdTrendRoute: ApiLabsProductsProductIdTrendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
